version: "3"
services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=openapi-typescript-express
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_DB=openapi-typescript-express
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
